#!/usr/bin/env python3
"""
Generate daily match preview blurbs via claude -p.
Run once per day (wired to albert-scheduler at 7am).
Output: previews.js  — loaded by index.html at page open.
"""
import subprocess, json, urllib.request, datetime, sys

BASE = "https://site.api.espn.com/apis/site/v2/sports/soccer/FIFA.WORLD"


def fetch_games(date_str: str) -> list:
    url = f"{BASE}/scoreboard?dates={date_str}"
    try:
        req = urllib.request.Request(url, headers={'User-Agent': 'Mozilla/5.0'})
        with urllib.request.urlopen(req, timeout=10) as r:
            data = json.loads(r.read())
    except Exception as e:
        print(f"ERROR fetching games: {e}", file=sys.stderr)
        return []
    games = []
    for ev in data.get('events', []):
        comp = (ev.get('competitions') or [{}])[0]
        teams = [c['team']['displayName'] for c in comp.get('competitors', [])]
        if len(teams) == 2:
            games.append({
                'id': ev.get('id', ''),
                'name': f"{teams[0]} vs {teams[1]}",
                'home': teams[0],
                'away': teams[1],
            })
    return games


def generate_preview(matchup: str) -> str:
    prompt = (
        f"Write exactly 2 punchy sentences as a World Cup match preview for: {matchup}. "
        "Draw on what you know about these national teams — their style, best-known players, "
        "and typical tournament strengths. Do not mention knowledge cutoffs or uncertainty. "
        "Just write the 2 sentences. Nothing else."
    )
    claude_cmd = r'C:\Users\tobri\AppData\Roaming\npm\claude.cmd'
    result = subprocess.run(
        [claude_cmd, '-p', prompt, '--model', 'claude-haiku-4-5-20251001'],
        capture_output=True, text=True, timeout=45, shell=False, encoding='utf-8'
    )
    if result.returncode != 0:
        print(f"  WARN claude -p failed: {result.stderr[:200]}", file=sys.stderr)
        return ''
    return result.stdout.strip()


def main():
    date_str = datetime.date.today().strftime('%Y%m%d')
    print(f"Fetching games for {date_str}...")
    games = fetch_games(date_str)

    if not games:
        print("No games today.")
        previews = {}
    else:
        print(f"Found {len(games)} games. Generating previews...")
        previews = {}
        for g in games:
            print(f"  {g['name']}...", end=' ', flush=True)
            text = generate_preview(g['name'])
            if text:
                previews[g['id']] = {'matchup': g['name'], 'text': text}
                print('OK')
            else:
                print('SKIP')

    out = (
        '// AUTO-GENERATED by generate_previews.py — do not edit manually\n'
        f'// Generated: {datetime.datetime.now().isoformat()}\n'
        f'// {len(previews)} previews\n\n'
        'const MATCH_PREVIEWS = ' + json.dumps(previews, indent=2, ensure_ascii=False) + ';\n'
    )
    out_path = 'C:/Users/tobri/AIAgency/clients/worldcup/previews.js'
    with open(out_path, 'w', encoding='utf-8') as f:
        f.write(out)
    print(f"Written: {out_path}")


if __name__ == '__main__':
    main()
