// AUTO-GENERATED by generate_player_data.py — do not edit manually
// 360 players across all 48 WC 2026 teams

const PLAYER_DATA = {
  "150451": {
    "club": "Lille"
  },
  "287572": {
    "club": "Paris FC"
  },
  "179187": {
    "club": "Lille"
  },
  "287078": {
    "club": "Nice"
  },
  "290517": {
    "club": "FC Twente"
  },
  "259743": {
    "club": "Marseille"
  },
  "341711": {
    "club": "Feyenoord Rotterdam"
  },
  "167192": {
    "club": "Marseille"
  },
  "145190": {
    "club": "Lyon"
  },
  "228262": {
    "club": "River Plate"
  },
  "153115": {
    "club": "Boca Juniors"
  },
  "174466": {
    "club": "Inter Miami CF"
  },
  "207343": {
    "club": "Real Betis"
  },
  "249299": {
    "club": "Liverpool"
  },
  "320760": {
    "club": "Strasbourg"
  },
  "45843": {
    "club": "Inter Miami CF"
  },
  "311743": {
    "club": "Palmeiras"
  },
  "172137": {
    "club": "Albirex Niigata"
  },
  "291697": {
    "club": "New York City FC"
  },
  "328541": {
    "club": "Feyenoord Rotterdam"
  },
  "392320": {
    "club": "Colorado Rapids"
  },
  "241031": {
    "club": "New York City FC"
  },
  "312261": {
    "club": "Machida Zelvia"
  },
  "169189": {
    "club": "Bayern Munich"
  },
  "333399": {
    "club": "PSV Eindhoven"
  },
  "166473": {
    "club": "Lille"
  },
  "318577": {
    "club": "Lille"
  },
  "174980": {
    "club": "Arsenal"
  },
  "340678": {
    "club": "Strasbourg"
  },
  "359651": {
    "club": "Lille"
  },
  "387044": {
    "club": "Lens"
  },
  "325410": {
    "club": "PSV Eindhoven"
  },
  "196876": {
    "club": "Liverpool"
  },
  "198983": {
    "club": "Grêmio"
  },
  "125514": {
    "club": "Flamengo"
  },
  "145405": {
    "club": "Flamengo"
  },
  "159047": {
    "club": "Paris Saint-Germain"
  },
  "170369": {
    "club": "Flamengo"
  },
  "236322": {
    "club": "Arsenal"
  },
  "234715": {
    "club": "Flamengo"
  },
  "306764": {
    "club": "Botafogo"
  },
  "132948": {
    "club": "Santos"
  },
  "269844": {
    "club": "Arsenal"
  },
  "357719": {
    "club": "Vasco da Gama"
  },
  "159382": {
    "club": "Orlando City SC"
  },
  "231059": {
    "club": "Inter Miami CF"
  },
  "230626": {
    "club": "Toronto FC"
  },
  "236721": {
    "club": "Bayern Munich"
  },
  "236890": {
    "club": "Chicago Fire FC"
  },
  "358975": {
    "club": "Nice"
  },
  "184221": {
    "club": "Toronto FC"
  },
  "270505": {
    "club": "LAFC"
  },
  "274296": {
    "club": "LAFC"
  },
  "340228": {
    "club": "Vancouver Whitecaps"
  },
  "280612": {
    "club": "Austin FC"
  },
  "286214": {
    "club": "LAFC"
  },
  "265874": {
    "club": "San Diego FC"
  },
  "180113": {
    "club": "Columbus Crew"
  },
  "227441": {
    "club": "PEC Zwolle"
  },
  "121842": {
    "club": "Atlético Nacional"
  },
  "166323": {
    "club": "Vélez Sarsfield"
  },
  "185147": {
    "club": "Atlas"
  },
  "164756": {
    "club": "Independiente"
  },
  "197401": {
    "club": "Nantes"
  },
  "270229": {
    "club": "Cruz Azul"
  },
  "82816": {
    "club": "Minnesota United FC"
  },
  "94976": {
    "club": "Athletico Paranaense"
  },
  "177780": {
    "club": "River Plate"
  },
  "208700": {
    "club": "Flamengo"
  },
  "239566": {
    "club": "Palmeiras"
  },
  "255295": {
    "club": "Rosario Central"
  },
  "307756": {
    "club": "River Plate"
  },
  "176058": {
    "club": "Instituto (Córdoba)"
  },
  "257390": {
    "club": "Bayern Munich"
  },
  "330924": {
    "club": "Vasco da Gama"
  },
  "336809": {
    "club": "Real Betis"
  },
  "211669": {
    "club": "Le Havre AC"
  },
  "174322": {
    "club": "Lille"
  },
  "340240": {
    "club": "Sunderland"
  },
  "345988": {
    "club": "Lille"
  },
  "147193": {
    "club": "Real Betis"
  },
  "276329": {
    "club": "Bayern Munich"
  },
  "305552": {
    "club": "Ajax Amsterdam"
  },
  "103485": {
    "club": "PSV Eindhoven"
  },
  "277128": {
    "club": "FC Dallas"
  },
  "324270": {
    "club": "Orlando City SC"
  },
  "127444": {
    "club": "Curaçao"
  },
  "262109": {
    "club": "VVV-Venlo"
  },
  "297542": {
    "club": "Telstar"
  },
  "178433": {
    "club": "Curaçao"
  },
  "188411": {
    "club": "Curaçao"
  },
  "224786": {
    "club": "PEC Zwolle"
  },
  "245918": {
    "club": "PSV Eindhoven"
  },
  "246281": {
    "club": "Curaçao"
  },
  "270807": {
    "club": "RKC Waalwijk"
  },
  "301456": {
    "club": "Sparta Rotterdam"
  },
  "317285": {
    "club": "Curaçao"
  },
  "335203": {
    "club": "NEC Nijmegen"
  },
  "138664": {
    "club": "Curaçao"
  },
  "216287": {
    "club": "FC Volendam"
  },
  "262738": {
    "club": "FC Den Bosch"
  },
  "273295": {
    "club": "RKC Waalwijk"
  },
  "276218": {
    "club": "Curaçao"
  },
  "306553": {
    "club": "Curaçao"
  },
  "359132": {
    "club": "Telstar"
  },
  "167213": {
    "club": "Curaçao"
  },
  "177058": {
    "club": "FC Volendam"
  },
  "178273": {
    "club": "Curaçao"
  },
  "188452": {
    "club": "Curaçao"
  },
  "297299": {
    "club": "Curaçao"
  },
  "301441": {
    "club": "Curaçao"
  },
  "310925": {
    "club": "Curaçao"
  },
  "277313": {
    "club": "PSV Eindhoven"
  },
  "305545": {
    "club": "Lyon"
  },
  "131726": {
    "club": "Liga de Quito"
  },
  "207921": {
    "club": "Huracán"
  },
  "251963": {
    "club": "Internacional"
  },
  "256560": {
    "club": "Atlético-MG"
  },
  "286665": {
    "club": "Tijuana"
  },
  "287005": {
    "club": "Paris Saint-Germain"
  },
  "292062": {
    "club": "Arsenal"
  },
  "262111": {
    "club": "Atlético-MG"
  },
  "270829": {
    "club": "Independiente del Valle"
  },
  "297150": {
    "club": "Pumas UNAM"
  },
  "358746": {
    "club": "River Plate"
  },
  "171771": {
    "club": "Pachuca"
  },
  "217079": {
    "club": "Huracán"
  },
  "277352": {
    "club": "Flamengo"
  },
  "281316": {
    "club": "Peñarol"
  },
  "318090": {
    "club": "Sunderland"
  },
  "319422": {
    "club": "Atlético-MG"
  },
  "236957": {
    "club": "Nice"
  },
  "173896": {
    "club": "Liverpool"
  },
  "238262": {
    "club": "Arsenal"
  },
  "251400": {
    "club": "Arsenal"
  },
  "142200": {
    "club": "Bayern Munich"
  },
  "280555": {
    "club": "Arsenal"
  },
  "293236": {
    "club": "Arsenal"
  },
  "164126": {
    "club": "Stade Rennais"
  },
  "344517": {
    "club": "Lens"
  },
  "196200": {
    "club": "Paris Saint-Germain"
  },
  "222793": {
    "club": "Bayern Munich"
  },
  "251634": {
    "club": "Liverpool"
  },
  "277385": {
    "club": "Arsenal"
  },
  "286831": {
    "club": "Bayern Munich"
  },
  "329690": {
    "club": "AS Monaco"
  },
  "345581": {
    "club": "Paris Saint-Germain"
  },
  "229744": {
    "club": "Paris Saint-Germain"
  },
  "328238": {
    "club": "Paris Saint-Germain"
  },
  "336388": {
    "club": "Paris Saint-Germain"
  },
  "84774": {
    "club": "Bayern Munich"
  },
  "188052": {
    "club": "Bayern Munich"
  },
  "174550": {
    "club": "Bayern Munich"
  },
  "190161": {
    "club": "Bayern Munich"
  },
  "303748": {
    "club": "Liverpool"
  },
  "303821": {
    "club": "Bayern Munich"
  },
  "359370": {
    "club": "Bayern Munich"
  },
  "231182": {
    "club": "Arsenal"
  },
  "264484": {
    "club": "AJ Auxerre"
  },
  "305669": {
    "club": "Stade Rennais"
  },
  "309638": {
    "club": "AJ Auxerre"
  },
  "357205": {
    "club": "Nice"
  },
  "266057": {
    "club": "AJ Auxerre"
  },
  "326183": {
    "club": "Saint-Étienne"
  },
  "333310": {
    "club": "Lyon"
  },
  "89090": {
    "club": "Bastia"
  },
  "310715": {
    "club": "Sochaux"
  },
  "188106": {
    "club": "Liga de Quito"
  },
  "218703": {
    "club": "Angers"
  },
  "235401": {
    "club": "Colorado Springs Switchbacks FC"
  },
  "320212": {
    "club": "AS Nancy Lorraine"
  },
  "297177": {
    "club": "El Paso Locomotive FC"
  },
  "333939": {
    "club": "Philadelphia Union"
  },
  "359946": {
    "club": "Real Hope"
  },
  "231098": {
    "club": "Toronto FC"
  },
  "265915": {
    "club": "Sunderland"
  },
  "275007": {
    "club": "US Quevilly"
  },
  "291608": {
    "club": "FC Dallas"
  },
  "304212": {
    "club": "AJ Auxerre"
  },
  "307861": {
    "club": "Almere City"
  },
  "287723": {
    "club": "Sarpsborg FK"
  },
  "325549": {
    "club": "FC Utrecht"
  },
  "313976": {
    "club": "Nashville SC"
  },
  "346636": {
    "club": "Strasbourg"
  },
  "255723": {
    "club": "Sanfrecce Hiroshima"
  },
  "312924": {
    "club": "Kashima Antlers"
  },
  "97111": {
    "club": "Bayern Munich"
  },
  "119082": {
    "club": "FC Tokyo"
  },
  "238004": {
    "club": "Ajax Amsterdam"
  },
  "238033": {
    "club": "Ajax Amsterdam"
  },
  "258270": {
    "club": "Le Havre AC"
  },
  "276279": {
    "club": "Feyenoord Rotterdam"
  },
  "152479": {
    "club": "Liverpool"
  },
  "253173": {
    "club": "Leeds United"
  },
  "238016": {
    "club": "NEC Nijmegen"
  },
  "265953": {
    "club": "Stade de Reims"
  },
  "274277": {
    "club": "Feyenoord Rotterdam"
  },
  "257489": {
    "club": "Stade Rennais"
  },
  "236368": {
    "club": "Santos"
  },
  "290899": {
    "club": "Guadalajara"
  },
  "132098": {
    "club": "Toluca"
  },
  "178746": {
    "club": "Cruz Azul"
  },
  "290414": {
    "club": "América"
  },
  "379193": {
    "club": "AZ Alkmaar"
  },
  "242614": {
    "club": "Guadalajara"
  },
  "276942": {
    "club": "Cruz Azul"
  },
  "283827": {
    "club": "América"
  },
  "303577": {
    "club": "River Plate"
  },
  "318554": {
    "club": "Seattle Sounders FC"
  },
  "389575": {
    "club": "Tijuana"
  },
  "193566": {
    "club": "Pumas UNAM"
  },
  "194308": {
    "club": "Guadalajara"
  },
  "229487": {
    "club": "Toluca"
  },
  "376110": {
    "club": "Guadalajara"
  },
  "240233": {
    "club": "Paris Saint-Germain"
  },
  "245243": {
    "club": "Marseille"
  },
  "297296": {
    "club": "PSV Eindhoven"
  },
  "195226": {
    "club": "Real Betis"
  },
  "304572": {
    "club": "PSV Eindhoven"
  },
  "373927": {
    "club": "Lille"
  },
  "378491": {
    "club": "Strasbourg"
  },
  "300912": {
    "club": "Real Betis"
  },
  "360062": {
    "club": "Sunderland"
  },
  "379012": {
    "club": "Strasbourg"
  },
  "301449": {
    "club": "Sunderland"
  },
  "157892": {
    "club": "Liverpool"
  },
  "264828": {
    "club": "Sunderland"
  },
  "240965": {
    "club": "PSV Eindhoven"
  },
  "274632": {
    "club": "Liverpool"
  },
  "282230": {
    "club": "Marseille"
  },
  "159255": {
    "club": "Corinthians"
  },
  "177042": {
    "club": "Ajax Amsterdam"
  },
  "249524": {
    "club": "Liverpool"
  },
  "282229": {
    "club": "Sunderland"
  },
  "101934": {
    "club": "Minnesota United FC"
  },
  "266554": {
    "club": "Wrexham"
  },
  "332367": {
    "club": "Portland Timbers"
  },
  "156146": {
    "club": "PEC Zwolle"
  },
  "228294": {
    "club": "Viking FK"
  },
  "297802": {
    "club": "Saint-Étienne"
  },
  "238088": {
    "club": "Bodo/Glimt"
  },
  "303281": {
    "club": "Viking FK"
  },
  "203669": {
    "club": "Arsenal"
  },
  "205924": {
    "club": "Bodo/Glimt"
  },
  "235789": {
    "club": "Bodo/Glimt"
  },
  "124521": {
    "club": "Nacional"
  },
  "328403": {
    "club": "Club Deportivo Marathón"
  },
  "138183": {
    "club": "Plaza Amador"
  },
  "216418": {
    "club": "Saprissa"
  },
  "271294": {
    "club": "Deportivo La Guaira"
  },
  "291014": {
    "club": "Academia Puerto Cabello"
  },
  "116825": {
    "club": "San Diego FC"
  },
  "201919": {
    "club": "Mazatlán FC"
  },
  "219508": {
    "club": "Pumas UNAM"
  },
  "238763": {
    "club": "FC Juarez"
  },
  "285452": {
    "club": "Minnesota United FC"
  },
  "102167": {
    "club": "Plaza Amador"
  },
  "155913": {
    "club": "Universidad de Concepción"
  },
  "195326": {
    "club": "León"
  },
  "267996": {
    "club": "Universidad Católica (Quito)"
  },
  "288563": {
    "club": "Acassuso"
  },
  "303538": {
    "club": "Cobresal"
  },
  "340539": {
    "club": "Universidad Católica (Quito)"
  },
  "164262": {
    "club": "Cerro Porteño"
  },
  "190375": {
    "club": "Club Olimpia"
  },
  "301648": {
    "club": "San Lorenzo"
  },
  "118395": {
    "club": "Palmeiras"
  },
  "119413": {
    "club": "Cerro Porteño"
  },
  "181657": {
    "club": "Atlético-MG"
  },
  "199101": {
    "club": "Grêmio"
  },
  "215401": {
    "club": "Sunderland"
  },
  "227682": {
    "club": "Lanús"
  },
  "399687": {
    "club": "Talleres (Córdoba)"
  },
  "20975": {
    "club": "Strasbourg"
  },
  "202501": {
    "club": "Vancouver Whitecaps"
  },
  "265977": {
    "club": "Orlando City SC"
  },
  "289046": {
    "club": "Palmeiras"
  },
  "297328": {
    "club": "Atlanta United FC"
  },
  "301516": {
    "club": "São Paulo"
  },
  "48128": {
    "club": "Atlanta United FC"
  },
  "154853": {
    "club": "Santos"
  },
  "208421": {
    "club": "Independiente"
  },
  "257754": {
    "club": "Independiente Rivadavia"
  },
  "287035": {
    "club": "Red Bull Bragantino"
  },
  "301653": {
    "club": "Palmeiras"
  },
  "290591": {
    "club": "Paris Saint-Germain"
  },
  "288897": {
    "club": "Paris Saint-Germain"
  },
  "355061": {
    "club": "Paris Saint-Germain"
  },
  "288896": {
    "club": "Paris Saint-Germain"
  },
  "104943": {
    "club": "Liverpool"
  },
  "231572": {
    "club": "Wrexham"
  },
  "197631": {
    "club": "Le Havre AC"
  },
  "241029": {
    "club": "Nice"
  },
  "213181": {
    "club": "Lyon"
  },
  "319161": {
    "club": "Nice"
  },
  "38721": {
    "club": "AS Monaco"
  },
  "253992": {
    "club": "AS Monaco"
  },
  "324991": {
    "club": "Sunderland"
  },
  "409016": {
    "club": "Bayern Munich"
  },
  "308524": {
    "club": "Bayern Munich"
  },
  "388522": {
    "club": "Paris Saint-Germain"
  },
  "351372": {
    "club": "Philadelphia Union"
  },
  "366883": {
    "club": "Molde"
  },
  "400594": {
    "club": "Chicago Fire FC"
  },
  "175921": {
    "club": "FC Tokyo"
  },
  "157688": {
    "club": "Bayern Munich"
  },
  "286268": {
    "club": "Kashima Antlers"
  },
  "274197": {
    "club": "Paris Saint-Germain"
  },
  "280061": {
    "club": "Feyenoord Rotterdam"
  },
  "336178": {
    "club": "Zhejiang Professional FC"
  },
  "149945": {
    "club": "LAFC"
  },
  "196176": {
    "club": "Arsenal"
  },
  "209581": {
    "club": "Arsenal"
  },
  "214596": {
    "club": "Paris Saint-Germain"
  },
  "287266": {
    "club": "Arsenal"
  },
  "133993": {
    "club": "AIK"
  },
  "250166": {
    "club": "Leeds United"
  },
  "312876": {
    "club": "FC Dallas"
  },
  "314164": {
    "club": "Malmö FF"
  },
  "357145": {
    "club": "Mjällby AIF"
  },
  "235662": {
    "club": "Liverpool"
  },
  "258906": {
    "club": "Arsenal"
  },
  "199381": {
    "club": "Lorient"
  },
  "136865": {
    "club": "Real Betis"
  },
  "149981": {
    "club": "Sunderland"
  },
  "222628": {
    "club": "AS Monaco"
  },
  "202099": {
    "club": "Stade Rennais"
  },
  "270641": {
    "club": "Leeds United"
  },
  "265099": {
    "club": "Lorient"
  },
  "265234": {
    "club": "Nice"
  },
  "405591": {
    "club": "Vancouver Whitecaps"
  },
  "252974": {
    "club": "New York City FC"
  },
  "303693": {
    "club": "Chicago Fire FC"
  },
  "303794": {
    "club": "New England Revolution"
  },
  "77072": {
    "club": "Toulouse"
  },
  "146290": {
    "club": "Charlotte FC"
  },
  "248276": {
    "club": "Orlando City SC"
  },
  "249768": {
    "club": "FC Cincinnati"
  },
  "266291": {
    "club": "PSV Eindhoven"
  },
  "216617": {
    "club": "Seattle Sounders FC"
  },
  "259653": {
    "club": "Leeds United"
  },
  "295771": {
    "club": "Vancouver Whitecaps"
  },
  "359542": {
    "club": "Columbus Crew"
  },
  "212824": {
    "club": "América"
  },
  "282643": {
    "club": "AS Monaco"
  },
  "289120": {
    "club": "PSV Eindhoven"
  },
  "108622": {
    "club": "Estudiantes de La Plata"
  },
  "184206": {
    "club": "Internacional"
  },
  "203067": {
    "club": "Monterrey"
  },
  "188368": {
    "club": "Flamengo"
  },
  "254007": {
    "club": "Palmeiras"
  },
  "254032": {
    "club": "River Plate"
  },
  "285756": {
    "club": "América"
  },
  "109962": {
    "club": "Palmeiras"
  },
  "179767": {
    "club": "Flamengo"
  },
  "251889": {
    "club": "Flamengo"
  },
  "287497": {
    "club": "Real Salt Lake"
  },
  "144325": {
    "club": "América"
  },
  "159042": {
    "club": "Tigres UANL"
  },
  "241466": {
    "club": "Cúcuta Deportivo"
  }
};

const LEAGUE_DATA = {
  "150451": "Ligue 1",
  "287572": "Ligue 1",
  "179187": "Ligue 1",
  "287078": "Ligue 1",
  "290517": "Eredivisie",
  "259743": "Ligue 1",
  "341711": "Eredivisie",
  "167192": "Ligue 1",
  "145190": "Ligue 1",
  "228262": "Liga Profesional",
  "153115": "Liga Profesional",
  "174466": "MLS",
  "207343": "La Liga",
  "249299": "Premier League",
  "320760": "Ligue 1",
  "45843": "MLS",
  "311743": "Brasileirão",
  "172137": "J1 League",
  "291697": "MLS",
  "328541": "Eredivisie",
  "392320": "MLS",
  "241031": "MLS",
  "312261": "J1 League",
  "169189": "Bundesliga",
  "333399": "Eredivisie",
  "166473": "Ligue 1",
  "318577": "Ligue 1",
  "174980": "Premier League",
  "340678": "Ligue 1",
  "359651": "Ligue 1",
  "387044": "Ligue 1",
  "325410": "Eredivisie",
  "196876": "Premier League",
  "198983": "Brasileirão",
  "125514": "Brasileirão",
  "145405": "Brasileirão",
  "159047": "Ligue 1",
  "170369": "Brasileirão",
  "236322": "Premier League",
  "234715": "Brasileirão",
  "306764": "Brasileirão",
  "132948": "Brasileirão",
  "269844": "Premier League",
  "357719": "Brasileirão",
  "159382": "MLS",
  "231059": "MLS",
  "230626": "MLS",
  "236721": "Bundesliga",
  "236890": "MLS",
  "358975": "Ligue 1",
  "184221": "MLS",
  "270505": "MLS",
  "274296": "MLS",
  "340228": "MLS",
  "280612": "MLS",
  "286214": "MLS",
  "265874": "MLS",
  "180113": "MLS",
  "227441": "Eredivisie",
  "121842": "Categoría Primera A",
  "166323": "Liga Profesional",
  "185147": "Liga MX",
  "164756": "Liga Profesional",
  "197401": "FRA.2",
  "270229": "Liga MX",
  "82816": "MLS",
  "94976": "BRA.2",
  "177780": "Liga Profesional",
  "208700": "Brasileirão",
  "239566": "Brasileirão",
  "255295": "Liga Profesional",
  "307756": "Liga Profesional",
  "176058": "Liga Profesional",
  "257390": "Bundesliga",
  "330924": "Brasileirão",
  "336809": "La Liga",
  "211669": "Ligue 1",
  "174322": "Ligue 1",
  "340240": "Premier League",
  "345988": "Ligue 1",
  "147193": "La Liga",
  "276329": "Bundesliga",
  "305552": "Eredivisie",
  "103485": "Eredivisie",
  "277128": "MLS",
  "324270": "MLS",
  "127444": "FIFA.FRIENDLY",
  "262109": "NED.2",
  "297542": "Eredivisie",
  "178433": "FIFA.FRIENDLY",
  "188411": "FIFA.FRIENDLY",
  "224786": "Eredivisie",
  "245918": "Eredivisie",
  "246281": "FIFA.FRIENDLY",
  "270807": "NED.2",
  "301456": "Eredivisie",
  "317285": "FIFA.FRIENDLY",
  "335203": "Eredivisie",
  "138664": "FIFA.FRIENDLY",
  "216287": "NED.2",
  "262738": "NED.2",
  "273295": "NED.2",
  "276218": "FIFA.FRIENDLY",
  "306553": "FIFA.FRIENDLY",
  "359132": "Eredivisie",
  "167213": "FIFA.FRIENDLY",
  "177058": "NED.2",
  "178273": "FIFA.FRIENDLY",
  "188452": "FIFA.FRIENDLY",
  "297299": "FIFA.FRIENDLY",
  "301441": "FIFA.FRIENDLY",
  "310925": "FIFA.FRIENDLY",
  "277313": "Eredivisie",
  "305545": "Ligue 1",
  "131726": "ECU.1",
  "207921": "Liga Profesional",
  "251963": "Brasileirão",
  "256560": "Brasileirão",
  "286665": "Liga MX",
  "287005": "Ligue 1",
  "292062": "Premier League",
  "262111": "Brasileirão",
  "270829": "ECU.1",
  "297150": "Liga MX",
  "358746": "Liga Profesional",
  "171771": "Liga MX",
  "217079": "Liga Profesional",
  "277352": "Brasileirão",
  "281316": "Primera División",
  "318090": "Premier League",
  "319422": "Brasileirão",
  "236957": "Ligue 1",
  "173896": "Premier League",
  "238262": "Premier League",
  "251400": "Premier League",
  "142200": "Bundesliga",
  "280555": "Premier League",
  "293236": "Premier League",
  "164126": "Ligue 1",
  "344517": "Ligue 1",
  "196200": "Ligue 1",
  "222793": "Bundesliga",
  "251634": "Premier League",
  "277385": "Premier League",
  "286831": "Bundesliga",
  "329690": "Ligue 1",
  "345581": "Ligue 1",
  "229744": "Ligue 1",
  "328238": "Ligue 1",
  "336388": "Ligue 1",
  "84774": "Bundesliga",
  "188052": "Bundesliga",
  "174550": "Bundesliga",
  "190161": "Bundesliga",
  "303748": "Premier League",
  "303821": "Bundesliga",
  "359370": "Bundesliga",
  "231182": "Premier League",
  "264484": "Ligue 1",
  "305669": "Ligue 1",
  "309638": "Ligue 1",
  "357205": "Ligue 1",
  "266057": "Ligue 1",
  "326183": "FRA.2",
  "333310": "Ligue 1",
  "89090": "FRA.2",
  "310715": "FRA.2",
  "188106": "ECU.1",
  "218703": "Ligue 1",
  "235401": "USA.USL.1",
  "320212": "FRA.2",
  "297177": "USA.USL.1",
  "333939": "MLS",
  "359946": "CONCACAF.CHAMPIONS",
  "231098": "MLS",
  "265915": "Premier League",
  "275007": "FRA.2",
  "291608": "MLS",
  "304212": "Ligue 1",
  "307861": "NED.2",
  "287723": "NOR.1",
  "325549": "Eredivisie",
  "313976": "MLS",
  "346636": "Ligue 1",
  "255723": "J1 League",
  "312924": "J1 League",
  "97111": "Bundesliga",
  "119082": "J1 League",
  "238004": "Eredivisie",
  "238033": "Eredivisie",
  "258270": "Ligue 1",
  "276279": "Eredivisie",
  "152479": "Premier League",
  "253173": "Premier League",
  "238016": "Eredivisie",
  "265953": "FRA.2",
  "274277": "Eredivisie",
  "257489": "Ligue 1",
  "236368": "Liga MX",
  "290899": "Liga MX",
  "132098": "Liga MX",
  "178746": "Liga MX",
  "290414": "Liga MX",
  "379193": "Eredivisie",
  "242614": "Liga MX",
  "276942": "Liga MX",
  "283827": "Liga MX",
  "303577": "Liga Profesional",
  "318554": "MLS",
  "389575": "Liga MX",
  "193566": "Liga MX",
  "194308": "Liga MX",
  "229487": "Liga MX",
  "376110": "Liga MX",
  "240233": "Ligue 1",
  "245243": "Ligue 1",
  "297296": "Eredivisie",
  "195226": "La Liga",
  "304572": "Eredivisie",
  "373927": "Ligue 1",
  "378491": "Ligue 1",
  "300912": "La Liga",
  "360062": "Premier League",
  "379012": "Ligue 1",
  "301449": "Premier League",
  "157892": "Premier League",
  "264828": "Premier League",
  "240965": "Eredivisie",
  "274632": "Premier League",
  "282230": "Ligue 1",
  "159255": "Brasileirão",
  "177042": "Eredivisie",
  "249524": "Premier League",
  "282229": "Premier League",
  "101934": "MLS",
  "266554": "ENG.2",
  "332367": "MLS",
  "156146": "Eredivisie",
  "228294": "NOR.1",
  "297802": "FRA.2",
  "238088": "NOR.1",
  "303281": "NOR.1",
  "203669": "Premier League",
  "205924": "NOR.1",
  "235789": "NOR.1",
  "124521": "Primera División",
  "328403": "Liga Nacional",
  "138183": "CONCACAF.CENTRAL.AMERICAN.CUP",
  "216418": "Liga Promerica",
  "271294": "Liga FUTVE",
  "291014": "Liga FUTVE",
  "116825": "MLS",
  "201919": "Liga MX",
  "219508": "Liga MX",
  "238763": "Liga MX",
  "285452": "MLS",
  "102167": "CONCACAF.CENTRAL.AMERICAN.CUP",
  "155913": "Primera División",
  "195326": "Liga MX",
  "267996": "ECU.1",
  "288563": "ARG.3",
  "303538": "Primera División",
  "340539": "ECU.1",
  "164262": "División Profesional",
  "190375": "División Profesional",
  "301648": "Liga Profesional",
  "118395": "Brasileirão",
  "119413": "División Profesional",
  "181657": "Brasileirão",
  "199101": "Brasileirão",
  "215401": "Premier League",
  "227682": "Liga Profesional",
  "399687": "Liga Profesional",
  "20975": "Ligue 1",
  "202501": "MLS",
  "265977": "MLS",
  "289046": "Brasileirão",
  "297328": "MLS",
  "301516": "Brasileirão",
  "48128": "MLS",
  "154853": "Brasileirão",
  "208421": "Liga Profesional",
  "257754": "Liga Profesional",
  "287035": "Brasileirão",
  "301653": "Brasileirão",
  "290591": "Ligue 1",
  "288897": "Ligue 1",
  "355061": "Ligue 1",
  "288896": "Ligue 1",
  "104943": "Premier League",
  "231572": "ENG.2",
  "197631": "Ligue 1",
  "241029": "Ligue 1",
  "213181": "Ligue 1",
  "319161": "Ligue 1",
  "38721": "Ligue 1",
  "253992": "Ligue 1",
  "324991": "Premier League",
  "409016": "Bundesliga",
  "308524": "Bundesliga",
  "388522": "Ligue 1",
  "351372": "MLS",
  "366883": "NOR.1",
  "400594": "MLS",
  "175921": "J1 League",
  "157688": "Bundesliga",
  "286268": "J1 League",
  "274197": "Ligue 1",
  "280061": "Eredivisie",
  "336178": "Chinese Super League",
  "149945": "MLS",
  "196176": "Premier League",
  "209581": "Premier League",
  "214596": "Ligue 1",
  "287266": "Premier League",
  "133993": "Allsvenskan",
  "250166": "Premier League",
  "312876": "MLS",
  "314164": "Allsvenskan",
  "357145": "Allsvenskan",
  "235662": "Premier League",
  "258906": "Premier League",
  "199381": "Ligue 1",
  "136865": "La Liga",
  "149981": "Premier League",
  "222628": "Ligue 1",
  "202099": "Ligue 1",
  "270641": "Premier League",
  "265099": "Ligue 1",
  "265234": "Ligue 1",
  "405591": "MLS",
  "252974": "MLS",
  "303693": "MLS",
  "303794": "MLS",
  "77072": "Ligue 1",
  "146290": "MLS",
  "248276": "MLS",
  "249768": "MLS",
  "266291": "Eredivisie",
  "216617": "MLS",
  "259653": "Premier League",
  "295771": "MLS",
  "359542": "MLS",
  "212824": "Liga MX",
  "282643": "Ligue 1",
  "289120": "Eredivisie",
  "108622": "Liga Profesional",
  "184206": "Brasileirão",
  "203067": "Liga MX",
  "188368": "Brasileirão",
  "254007": "Brasileirão",
  "254032": "Liga Profesional",
  "285756": "Liga MX",
  "109962": "Brasileirão",
  "179767": "Brasileirão",
  "251889": "Brasileirão",
  "287497": "MLS",
  "144325": "Liga MX",
  "159042": "Liga MX",
  "241466": "Categoría Primera A"
};