// AUTO-GENERATED by generate_previews.py — do not edit manually
// Generated: 2026-06-16T09:23:08.961399
// 3 previews

const MATCH_PREVIEWS = {
  "760432": {
    "matchup": "France vs Senegal",
    "text": "France's attacking firepower and World Cup pedigree clash with Senegal's disciplined, counter-attacking defense that thrives on suffocating possession and explosive breaks. The African dark horses can steal it if they stay compact and strike fast, but Les Bleus' tournament experience and relentless tempo should control the tempo and finish decisively."
  },
  "760430": {
    "matchup": "Iraq vs Norway",
    "text": "Norway's precision passing and controlled possession will face Iraq's compact, physical defense and counter-attacking urgency in a classic European technique vs. Asian grit matchup. The Iraqis need disciplined defending to frustrate the Norwegians' rhythm; Norway must break through without overcommitting and getting caught on the break."
  },
  "760433": {
    "matchup": "Argentina vs Algeria",
    "text": "Argentina's technical mastery and tournament pedigree will test Algeria's disciplined defensive shape, but the African side's compact pressing and pace on the break could expose vulnerable spaces in the Argentine backline. Expect Messi (or Argentina's current attacking focal point) to dictate tempo in midfield while Algeria looks to stay compact and punish any transition opportunities."
  }
};
