const WIKI_CLUBS = {
"matej kovar": "PSV Eindhoven",
"david zima": "Slavia Prague",
"tomas holes": "Slavia Prague",
"robin hranac": "TSG Hoffenheim",
"vladimir coufal": "TSG Hoffenheim",
"stepan chaloupek": "Slavia Prague",
"ladislav krejci": "Wolverhampton Wanderers",
"vladimir darida": "Hradec Králové",
"adam hlozek": "TSG Hoffenheim",
"patrik schick": "Bayer Leverkusen",
"jan kuchta": "Sparta Prague",
"lukas cerv": "Viktoria Plzeň",
"mojmir chytil": "Slavia Prague",
"david jurasek": "Slavia Prague",
"pavel sulc": "Lyon",
"jindrich stanek": "Slavia Prague",
"lukas provod": "Slavia Prague",
"michal sadilek": "Slavia Prague",
"tomas chory": "Slavia Prague",
"jaroslav zeleny": "Sparta Prague",
"david doudera": "Slavia Prague",
"tomas soucek": "West Ham United",
"lukas hornicek": "Braga",
"alexandr sojka": "Viktoria Plzeň",
"hugo sochurek": "Sparta Prague",
"denis visinsky": "Viktoria Plzeň",
"raul rangel": "Guadalajara",
"jorge sanchez": "PAOK",
"cesar montes": "Lokomotiv Moscow",
"edson alvarez": "Fenerbahçe",
"johan vasquez": "Genoa",
"erik lira": "Cruz Azul",
"luis romo": "Guadalajara",
"alvaro fidalgo": "Real Betis",
"raul jimenez": "Fulham",
"alexis vega": "Toluca",
"santiago gimenez": "Milan",
"carlos acevedo": "Santos Laguna",
"guillermo ochoa": "AEL Limassol",
"armando gonzalez": "Guadalajara",
"israel reyes": "América",
"julian quinones": "Al-Qadsiah",
"orbelin pineda": "AEK Athens",
"obed vargas": "Atlético Madrid",
"gilberto mora": "Tijuana",
"mateo chavez": "AZ",
"cesar huerta": "Anderlecht",
"guillermo martinez": "Pumas UNAM",
"jesus gallardo": "Toluca",
"luis chavez": "Dynamo Moscow",
"roberto alvarado": "Guadalajara",
"brian gutierrez": "Guadalajara",
"ronwen williams": "Mamelodi Sundowns",
"thabang matuludi": "Polokwane City",
"khulumani ndamane": "Mamelodi Sundowns",
"teboho mokoena": "Mamelodi Sundowns",
"thalente mbatha": "Orlando Pirates",
"aubrey modiba": "Mamelodi Sundowns",
"oswin appollis": "Orlando Pirates",
"tshepang moremi": "Orlando Pirates",
"lyle foster": "Burnley",
"relebohile mofokeng": "Orlando Pirates",
"themba zwane": "Mamelodi Sundowns",
"thapelo maseko": "AEL Limassol",
"sphephelo sithole": "Tondela",
"mbekezeli mbokazi": "Chicago Fire FC",
"iqraam rayners": "Mamelodi Sundowns",
"sipho chaine": "Orlando Pirates",
"evidence makgopa": "Orlando Pirates",
"samukele kabini": "Molde",
"nkosinathi sibisi": "Orlando Pirates",
"khuliso mudau": "Mamelodi Sundowns",
"ime okon": "Hannover 96",
"ricardo goss": "Siwelele",
"jayden adams": "Mamelodi Sundowns",
"olwethu makhanya": "Philadelphia Union",
"kamogelo sebelebele": "Orlando Pirates",
"bradley cross": "Kaizer Chiefs",
"kim seunggyu": "FC Tokyo",
"lee hanbeom": "Midtjylland",
"lee gihyuk": "Gangwon FC",
"kim minjae": "Bayern Munich",
"kim taehyeon": "Kashima Antlers",
"hwang inbeom": "Feyenoord",
"son heungmin": "Los Angeles FC",
"paik seungho": "Birmingham City",
"cho guesung": "Midtjylland",
"lee jaesung": "Mainz 05",
"hwang heechan": "Wolverhampton Wanderers",
"song bumkeun": "Jeonbuk Hyundai Motors",
"lee taeseok": "Austria Wien",
"cho wije": "Jeonbuk Hyundai Motors",
"kim moonhwan": "Daejeon Hana Citizen",
"park jinseob": "Zhejiang",
"bae junho": "Stoke City",
"oh hyeongyu": "Beşiktaş",
"lee kangin": "Paris Saint-Germain",
"yang hyunjun": "Celtic",
"jo hyeonwoo": "Ulsan HD",
"seol youngwoo": "Red Star Belgrade",
"jens castrop": "Borussia Mönchengladbach",
"kim jingyu": "Jeonbuk Hyundai Motors",
"eom jisung": "Swansea City",
"lee donggyeong": "Ulsan HD",
"nikola vasilj": "FC St. Pauli",
"nihad mujakic": "Gaziantep",
"dennis hadzikadunic": "Sampdoria",
"tarik muharemovic": "Sassuolo",
"sead kolasinac": "Atalanta",
"benjamin tahirovic": "Brøndby",
"amar dedic": "Benfica",
"armin gigovic": "Young Boys",
"samed bazdar": "Jagiellonia Białystok",
"ermedin demirovic": "VfB Stuttgart",
"edin dzeko": "Schalke 04",
"mladen jurkas": "Borac Banja Luka",
"ivan basic": "Astana",
"ivan sunjic": "Pafos",
"amar memic": "Viktoria Plzeň",
"amir hadziahmetovic": "Hull City",
"dzenis burnic": "Karlsruher SC",
"nikola katic": "Schalke 04",
"kerim alajbegovic": "Red Bull Salzburg",
"esmir bajraktarevic": "PSV Eindhoven",
"stjepan radeljic": "Rijeka",
"martin zlomislic": "Rijeka",
"haris tabakovic": "Borussia Mönchengladbach",
"arjan malic": "Sturm Graz",
"jovo lukic": "Universitatea Cluj",
"ermin mahmic": "Slovan Liberec",
"dayne st clair": "Inter Miami CF",
"alistair johnston": "Celtic",
"alfie jones": "Middlesbrough",
"luc de fougerolles": "Dender",
"joel waterman": "Chicago Fire FC",
"mathieu choiniere": "Los Angeles FC",
"stephen eustaquio": "Los Angeles FC",
"ismael kone": "Sassuolo",
"cyle larin": "Southampton",
"jonathan david": "Juventus",
"liam millar": "Hull City",
"tani oluwaseyi": "Villarreal",
"derek cornelius": "Rangers",
"jacob shaffelburg": "Los Angeles FC",
"moise bombito": "Nice",
"maxime crepeau": "Orlando City SC",
"tajon buchanan": "Villarreal",
"owen goodman": "Barnsley",
"alphonso davies": "Bayern Munich",
"ali ahmed": "Norwich City",
"jonathan osorio": "Toronto FC",
"richie laryea": "Toronto FC",
"niko sigur": "Hajduk Split",
"promise david": "Union Saint-Gilloise",
"nathan saliba": "Anderlecht",
"jayden nelson": "Austin FC",
"mahmud abunada": "Al-Rayyan",
"pedro miguel": "Al-Sadd",
"lucas mendes": "Al-Wakrah",
"issa laye": "Al-Arabi",
"jassem gaber": "Al-Rayyan",
"abdulaziz hatem": "Al-Rayyan",
"ahmed alaaeldin": "Al-Rayyan",
"edmilson junior": "Al-Duhail",
"mohammed muntari": "Al-Gharafa",
"hassan alhaydos": "Al-Sadd",
"akram afif": "Al-Sadd",
"karim boudiaf": "Al-Duhail",
"ayoub aloui": "Al-Gharafa",
"homam ahmed": "Cultural Leonesa",
"yusuf abdurisag": "Al-Wakrah",
"boualem khoukhi": "Al-Sadd",
"ahmed alganehi": "Al-Gharafa",
"sultan albrake": "Al-Duhail",
"almoez ali": "Al-Duhail",
"ahmed fathy": "Al-Arabi",
"salah zakaria": "Al-Duhail",
"meshaal barsham": "Al-Sadd",
"assim madibo": "Al-Wakrah",
"tahsin jamshid": "Al-Duhail",
"alhashmi alhussain": "Al-Arabi",
"mohamed manai": "Al-Shamal",
"gregor kobel": "Borussia Dortmund",
"miro muheim": "Hamburger SV",
"silvan widmer": "Mainz 05",
"nico elvedi": "Borussia Mönchengladbach",
"manuel akanji": "Inter Milan",
"denis zakaria": "Monaco",
"breel embolo": "Rennes",
"remo freuler": "Bologna",
"johan manzambi": "SC Freiburg",
"granit xhaka": "Sunderland",
"dan ndoye": "Nottingham Forest",
"yvon mvogo": "Lorient",
"ricardo rodriguez": "Real Betis",
"ardon jashari": "Milan",
"djibril sow": "Sevilla",
"christian fassnacht": "Young Boys",
"ruben vargas": "Sevilla",
"eray comert": "Valencia",
"noah okafor": "Leeds United",
"michel aebischer": "Pisa",
"marvin keller": "Young Boys",
"fabian rieder": "FC Augsburg",
"zeki amdouni": "Burnley",
"aurele amenda": "Eintracht Frankfurt",
"luca jaquez": "VfB Stuttgart",
"cedric itten": "Fortuna Düsseldorf",
"alisson": "Liverpool",
"ederson silva": "Atalanta",
"gabriel magalhaes": "Arsenal",
"marquinhos": "Paris Saint-Germain",
"casemiro": "Manchester United",
"alex sandro": "Flamengo",
"vinicius junior": "Real Madrid",
"bruno guimaraes": "Newcastle United",
"matheus cunha": "Manchester United",
"neymar": "Santos",
"raphinha": "Barcelona",
"weverton": "Grêmio",
"danilo luiz": "Flamengo",
"bremer": "Juventus",
"leo pereira": "Flamengo",
"douglas santos": "Zenit Saint Petersburg",
"fabinho": "Al-Ittihad",
"danilo santos": "Botafogo",
"endrick": "Lyon",
"lucas paqueta": "Flamengo",
"luiz henrique": "Zenit Saint Petersburg",
"gabriel martinelli": "Arsenal",
"ederson moraes": "Fenerbahçe",
"roger ibanez": "Al-Ahli",
"igor thiago": "Brentford",
"rayan": "Bournemouth",
"johny placide": "Bastia",
"carlens arcus": "Angers",
"keeto thermoncy": "Young Boys",
"ricardo ade": "LDU Quito",
"hannes delcroix": "Lugano",
"carl sainte": "El Paso Locomotive FC",
"derrick etienne jr": "Toronto FC",
"martin experience": "Nancy",
"duckens nazon": "Esteghlal",
"jeanricner bellegarde": "Wolverhampton Wanderers",
"louicius deedson": "FC Dallas",
"alexandre pierre": "Sochaux",
"duke lacroix": "Colorado Springs Switchbacks FC",
"garven metusala": "Colorado Springs Switchbacks FC",
"ruben providence": "Almere City",
"lenny joseph": "Ferencváros",
"danley jean jacques": "Philadelphia Union",
"wilson isidor": "Sunderland",
"yassin fortune": "Vizela",
"frantzdy pierrot": "Çaykur Rizespor",
"josue casimir": "Auxerre",
"jeankevin duverne": "Gent",
"josue duverger": "Cosmos Koblenz",
"wilguens paugain": "Zulte Waregem",
"dominique simon": "Tatran Prešov",
"woodensky pierre": "Violette",
"yassine bounou": "Al-Hilal",
"achraf hakimi": "Paris Saint-Germain",
"noussair mazraoui": "Manchester United",
"sofyan amrabat": "Real Betis",
"marwane saadane": "Al-Fateh",
"ayyoub bouaddi": "Lille",
"chemsdine talbi": "Sunderland",
"azzedine ounahi": "Girona",
"soufiane rahimi": "Al Ain",
"brahim diaz": "Real Madrid",
"ismael saibari": "PSV Eindhoven",
"munir mohamedi": "RS Berkane",
"zakaria el ouahdi": "Genk",
"issa diop": "Fulham",
"samir el mourabet": "Strasbourg",
"gessime yassine": "Strasbourg",
"amine sbai": "Angers",
"chadi riad": "Crystal Palace",
"youssef belammari": "Al Ahly",
"ayoub el kaabi": "Olympiacos",
"ayoube amaimouni": "Eintracht Frankfurt",
"ahmed reda tagnaouti": "AS FAR",
"bilal el khannouss": "VfB Stuttgart",
"neil el aynaoui": "Roma",
"redouane halhal": "Mechelen",
"anass salaheddine": "PSV Eindhoven",
"angus gunn": "Nottingham Forest",
"aaron hickey": "Brentford",
"andy robertson": "Liverpool",
"scott mctominay": "Napoli",
"grant hanley": "Hibernian",
"kieran tierney": "Celtic",
"john mcginn": "Aston Villa",
"tyler fletcher": "Manchester United",
"lyndon dykes": "Charlton Athletic",
"che adams": "Torino",
"ryan christie": "Bournemouth",
"liam kelly": "Rangers",
"jack hendry": "Al-Ettifaq",
"ross stewart": "Southampton",
"john souttar": "Rangers",
"dominic hyam": "Wrexham",
"ben gannondoak": "Bournemouth",
"george hirst": "Ipswich Town",
"lewis ferguson": "Bologna",
"lawrence shankland": "Heart of Midlothian",
"craig gordon": "Heart of Midlothian",
"nathan patterson": "Everton",
"kenny mclean": "Norwich City",
"anthony ralston": "Celtic",
"findlay curtis": "Kilmarnock",
"scott mckenna": "Dinamo Zagreb",
"mathew ryan": "Levante",
"milos degenek": "APOEL",
"alessandro circati": "Parma",
"jacob italiano": "Grazer AK",
"jordan bos": "Feyenoord",
"jason geria": "Albirex Niigata",
"mathew leckie": "Melbourne City",
"connor metcalfe": "FC St. Pauli",
"mohamed toure": "Norwich City",
"ajdin hrustic": "Heracles Almelo",
"awer mabil": "Castellón",
"paul izzo": "Randers",
"aiden oneill": "New York City FC",
"cammy devlin": "Heart of Midlothian",
"kai trewin": "New York City FC",
"aziz behich": "Melbourne City",
"nestory irankunda": "Watford",
"patrick beach": "Melbourne City",
"harry souttar": "Leicester City",
"cristian volpato": "Sassuolo",
"cameron burgess": "Swansea City",
"jackson irvine": "FC St. Pauli",
"nishan velupillay": "Melbourne Victory",
"paul okonengstler": "Sydney FC",
"lucas herrington": "Colorado Rapids",
"tete yengi": "Machida Zelvia",
"gatito fernandez": "Cerro Porteño",
"gustavo velazquez": "Cerro Porteño",
"omar alderete": "Sunderland",
"juan jose caceres": "Dynamo Moscow",
"fabian balbuena": "Grêmio",
"junior alonso": "Atlético Mineiro",
"ramon sosa": "Palmeiras",
"diego gomez": "Brighton & Hove Albion",
"antonio sanabria": "Cremonese",
"miguel almiron": "Atlanta United FC",
"mauricio": "Palmeiras",
"orlando gill": "San Lorenzo",
"jose canale": "Lanús",
"andres cubas": "Vancouver Whitecaps FC",
"gustavo gomez": "Palmeiras",
"damian bobadilla": "São Paulo",
"kaku": "Al Ain",
"alex arce": "Independiente Rivadavia",
"julio enciso": "Strasbourg",
"braian ojeda": "Orlando City SC",
"gabriel avalos": "Independiente",
"gaston olveira": "Olimpia",
"matias galarza": "Atlanta United FC",
"gustavo caballero": "Portsmouth",
"isidro pitta": "Red Bull Bragantino",
"alexandro maidana": "Talleres",
"mert gunok": "Fenerbahçe",
"zeki celik": "Roma",
"merih demiral": "Al-Ahli",
"caglar soyuncu": "Fenerbahçe",
"salih ozcan": "Borussia Dortmund",
"orkun kokcu": "Beşiktaş",
"kerem akturkoglu": "Fenerbahçe",
"arda guler": "Real Madrid",
"deniz gul": "Porto",
"hakan calhanoglu": "Inter Milan",
"kenan yildiz": "Juventus",
"altay bayindir": "Manchester United",
"eren elmali": "Galatasaray",
"abdulkerim bardakci": "Galatasaray",
"ozan kabak": "TSG Hoffenheim",
"ismail yuksek": "Fenerbahçe",
"irfan can kahveci": "Kasımpaşa",
"mert muldur": "Fenerbahçe",
"yunus akgun": "Galatasaray",
"ferdi kadioglu": "Brighton & Hove Albion",
"baris alper yilmaz": "Galatasaray",
"kaan ayhan": "Galatasaray",
"ugurcan cakir": "Galatasaray",
"oguz aydin": "Fenerbahçe",
"samet akaydin": "Çaykur Rizespor",
"can uzun": "Eintracht Frankfurt",
"matt turner": "New England Revolution",
"sergino dest": "PSV Eindhoven",
"chris richards": "Crystal Palace",
"tyler adams": "Bournemouth",
"antonee robinson": "Fulham",
"auston trusty": "Celtic",
"giovanni reyna": "Borussia Mönchengladbach",
"weston mckennie": "Juventus",
"ricardo pepi": "PSV Eindhoven",
"christian pulisic": "Milan",
"brenden aaronson": "Leeds United",
"miles robinson": "FC Cincinnati",
"tim ream": "Charlotte FC",
"sebastian berhalter": "Vancouver Whitecaps FC",
"cristian roldan": "Seattle Sounders FC",
"alex freeman": "Villarreal",
"malik tillman": "Bayer Leverkusen",
"max arfsten": "Columbus Crew",
"haji wright": "Coventry City",
"folarin balogun": "Monaco",
"timothy weah": "Marseille",
"mark mckenzie": "Toulouse",
"joe scally": "Borussia Mönchengladbach",
"matt freese": "New York City FC",
"chris brady": "Chicago Fire FC",
"alejandro zendejas": "América",
"eloy room": "Miami FC",
"shurandy sambo": "Sparta Rotterdam",
"jurien gaari": "Abha",
"roshon van eijma": "RKC Waalwijk",
"sherel floranus": "PEC Zwolle",
"godfried roemeratoe": "RKC Waalwijk",
"juninho bacuna": "Volendam",
"livano comenencia": "Zürich",
"jurgen locadia": "Miami FC",
"leandro bacuna": "Iğdır",
"jeremy antonisse": "Kifisia",
"sontje hansen": "Middlesbrough",
"tyrese noslin": "Telstar",
"kenji gorre": "Maccabi Haifa",
"arjany martha": "Rotherham United",
"jearl margaritha": "Beveren",
"brandley kuwas": "Volendam",
"armando obispo": "PSV Eindhoven",
"gervane kastaneer": "Terengganu",
"joshua brenet": "Kayserispor",
"tahith chong": "Sheffield United",
"kevin felida": "Den Bosch",
"riechedly bazoer": "Konyaspor",
"deveron fonville": "NEC",
"tyrick bodak": "Telstar",
"trevor doornbusch": "VVV-Venlo",
"hernan galindez": "Huracán",
"felix torres": "Internacional",
"piero hincapie": "Arsenal",
"joel ordonez": "Club Brugge",
"jordy alcivar": "Independiente del Valle",
"willian pacho": "Paris Saint-Germain",
"pervis estupinan": "Milan",
"anthony valencia": "Antwerp",
"john yeboah": "Venezia",
"kendry paez": "River Plate",
"kevin rodriguez": "Union Saint-Gilloise",
"moises ramirez": "Kifisia",
"enner valencia": "Pachuca",
"alan minda": "Atlético Mineiro",
"pedro vite": "Pumas UNAM",
"jordy caicedo": "Huracán",
"angelo preciado": "Atlético Mineiro",
"denil castillo": "Midtjylland",
"gonzalo plata": "Flamengo",
"nilson angulo": "Sunderland",
"alan franco": "Atlético Mineiro",
"gonzalo valle": "LDU Quito",
"moises caicedo": "Chelsea",
"jeremy arevalo": "VfB Stuttgart",
"jackson porozo": "Tijuana",
"yaimar medina": "Genk",
"manuel neuer": "Bayern Munich",
"antonio rudiger": "Real Madrid",
"waldemar anton": "Borussia Dortmund",
"jonathan tah": "Bayern Munich",
"aleksandar pavlovic": "Bayern Munich",
"joshua kimmich": "Bayern Munich",
"kai havertz": "Arsenal",
"leon goretzka": "Bayern Munich",
"jamie leweling": "VfB Stuttgart",
"jamal musiala": "Bayern Munich",
"nick woltemade": "Newcastle United",
"oliver baumann": "TSG Hoffenheim",
"pascal gro": "Brighton & Hove Albion",
"maximilian beier": "Borussia Dortmund",
"nico schlotterbeck": "Borussia Dortmund",
"angelo stiller": "VfB Stuttgart",
"florian wirtz": "Liverpool",
"nathaniel brown": "Eintracht Frankfurt",
"leroy sane": "Galatasaray",
"nadiem amiri": "Mainz 05",
"alexander nubel": "VfB Stuttgart",
"david raum": "RB Leipzig",
"felix nmecha": "Borussia Dortmund",
"malick thiaw": "Newcastle United",
"assan ouedraogo": "RB Leipzig",
"deniz undav": "VfB Stuttgart",
"yahia fofana": "Çaykur Rizespor",
"ousmane diomande": "Sporting CP",
"ghislain konan": "Gil Vicente",
"jean michael seri": "Maribor",
"wilfried singo": "Galatasaray",
"seko fofana": "Porto",
"odilon kossounou": "Atalanta",
"franck kessie": "Al-Ahli",
"angeyoan bonny": "Inter Milan",
"simon adingra": "Monaco",
"yan diomande": "RB Leipzig",
"elye wahi": "Nice",
"christopher operi": "İstanbul Başakşehir",
"oumar diakite": "Cercle Brugge",
"amad diallo": "Manchester United",
"mohamed kone": "Charleroi",
"guela doue": "Strasbourg",
"ibrahim sangare": "Nottingham Forest",
"nicolas pepe": "Villarreal",
"emmanuel agbadou": "Beşiktaş",
"evan ndicka": "Roma",
"evann guessand": "Crystal Palace",
"alban lafont": "Panathinaikos",
"bazoumana toure": "TSG Hoffenheim",
"parfait guiagon": "Charleroi",
"christ inao oulai": "Trabzonspor",
"zion suzuki": "Parma",
"yukinari sugawara": "Werder Bremen",
"shogo taniguchi": "Sint-Truiden",
"ko itakura": "Ajax",
"yuto nagatomo": "FC Tokyo",
"shuto machino": "Borussia Mönchengladbach",
"ao tanaka": "Leeds United",
"takefusa kubo": "Real Sociedad",
"keisuke goto": "Sint-Truiden",
"ritsu doan": "Eintracht Frankfurt",
"daizen maeda": "Celtic",
"keisuke osako": "Sanfrecce Hiroshima",
"keito nakamura": "Reims",
"junya ito": "Genk",
"daichi kamada": "Crystal Palace",
"tsuyoshi watanabe": "Feyenoord",
"yuito suzuki": "SC Freiburg",
"ayase ueda": "Feyenoord",
"koki ogawa": "NEC",
"ayumu seko": "Le Havre",
"hiroki ito": "Bayern Munich",
"takehiro tomiyasu": "Ajax",
"tomoki hayakawa": "Kashima Antlers",
"kaishu sano": "Mainz 05",
"junnosuke suzuki": "Copenhagen",
"kento shiogai": "VfL Wolfsburg",
"bart verbruggen": "Brighton & Hove Albion",
"lutsharel geertruida": "Sunderland",
"marten de roon": "Atalanta",
"virgil van dijk": "Liverpool",
"nathan ake": "Manchester City",
"jan paul van hecke": "Brighton & Hove Albion",
"justin kluivert": "Bournemouth",
"ryan gravenberch": "Liverpool",
"wout weghorst": "Ajax",
"memphis depay": "Corinthians",
"cody gakpo": "Liverpool",
"mats wieffer": "Brighton & Hove Albion",
"robin roefs": "Sunderland",
"tijjani reijnders": "Manchester City",
"micky van de ven": "Tottenham Hotspur",
"guus til": "PSV Eindhoven",
"noa lang": "Galatasaray",
"donyell malen": "Roma",
"brian brobbey": "Sunderland",
"teun koopmeiners": "Juventus",
"frenkie de jong": "Barcelona",
"denzel dumfries": "Inter Milan",
"mark flekken": "Bayer Leverkusen",
"crysencio summerville": "West Ham United",
"jorrel hato": "Chelsea",
"quinten timber": "Marseille",
"jacob widell zetterstrom": "Derby County",
"gustaf lagerbielke": "Braga",
"victor lindelof": "Aston Villa",
"isak hien": "Atalanta",
"gabriel gudmundsson": "Leeds United",
"herman johansson": "FC Dallas",
"lucas bergvall": "Tottenham Hotspur",
"daniel svensson": "Borussia Dortmund",
"alexander isak": "Liverpool",
"benjamin nygren": "Celtic",
"anthony elanga": "Newcastle United",
"viktor johansson": "Stoke City",
"ken sema": "Pafos",
"hjalmar ekdal": "Burnley",
"carl starfelt": "Celta Vigo",
"jesper karlstrom": "Udinese",
"viktor gyokeres": "Arsenal",
"yasin ayari": "Brighton & Hove Albion",
"mattias svanberg": "VfL Wolfsburg",
"eric smith": "FC St. Pauli",
"alexander bernhardsson": "Holstein Kiel",
"besfort zeneli": "Union Saint-Gilloise",
"kristoffer nordfeldt": "AIK",
"elliot stroud": "Mjällby AIF",
"gustaf nilsson": "Club Brugge",
"taha ali": "Malmö FF",
"mouhib chamakh": "Club Africain",
"ali abdi": "Nice",
"montassar talbi": "Lorient",
"omar rekik": "Maribor",
"adem arous": "Kasımpaşa",
"dylan bronn": "Servette",
"elias achouri": "Copenhagen",
"elias saad": "Hannover 96",
"hazem mastouri": "Dynamo Makhachkala",
"hannibal mejbri": "Burnley",
"ismael gharbi": "FC Augsburg",
"mortadha ben ouanes": "Kasımpaşa",
"rani khedira": "Union Berlin",
"khalil ayari": "Paris Saint-Germain",
"hadj mahmoud": "Lugano",
"aymen dahmen": "CS Sfaxien",
"ellyes skhiri": "Eintracht Frankfurt",
"rayan elloumi": "Vancouver Whitecaps FC",
"firas chaouat": "Club Africain",
"yan valery": "Young Boys",
"mohamed amine ben hamida": "Espérance de Tunis",
"sabri ben hessen": "Étoile du Sahel",
"moutaz neffati": "IFK Norrköping",
"raed chikhaoui": "US Monastir",
"anis ben slimane": "Norwich City",
"sebastian tounekti": "Celtic",
"thibaut courtois": "Real Madrid",
"zeno debast": "Sporting CP",
"arthur theate": "Eintracht Frankfurt",
"brandon mechele": "Club Brugge",
"maxim de cuyper": "Brighton & Hove Albion",
"axel witsel": "Girona",
"kevin de bruyne": "Napoli",
"youri tielemans": "Aston Villa",
"romelu lukaku": "Napoli",
"leandro trossard": "Arsenal",
"jeremy doku": "Manchester City",
"senne lammens": "Manchester United",
"mike penders": "Strasbourg",
"dodi lukebakio": "Benfica",
"thomas meunier": "Lille",
"koni de winter": "Milan",
"charles de ketelaere": "Atalanta",
"joaquin seys": "Club Brugge",
"diego moreira": "Strasbourg",
"hans vanaken": "Club Brugge",
"timothy castagne": "Fulham",
"alexis saelemaekers": "Milan",
"nicolas raskin": "Rangers",
"amadou onana": "Aston Villa",
"nathan ngoy": "Lille",
"matias fernandezpardo": "Lille",
"mohamed el shenawy": "Al Ahly",
"yasser ibrahim": "Al Ahly",
"mohamed hany": "Al Ahly",
"hossam abdelmaguid": "Zamalek",
"ramy rabia": "Al Ain",
"mohamed abdelmonem": "Nice",
"trezeguet": "Al Ahly",
"emam ashour": "Al Ahly",
"hamza abdelkarim": "Barcelona B",
"mohamed salah": "Liverpool",
"mostafa ziko": "Pyramids",
"haissem hassan": "Oviedo",
"ahmed fatouh": "Zamalek",
"hamdy fathy": "Al-Wakrah",
"karim hafez": "Pyramids",
"el mahdy soliman": "Zamalek",
"mohanad lasheen": "Pyramids",
"nabil emad": "Al-Najma",
"marwan attia": "Al Ahly",
"ibrahim adel": "Nordsjælland",
"mahmoud saber": "ZED",
"omar marmoush": "Manchester City",
"mostafa shobeir": "Al Ahly",
"tarek alaa": "ZED",
"zizo": "Al Ahly",
"mohamed alaa": "El Gouna",
"alireza beiranvand": "Tractor",
"saleh hardani": "Esteghlal",
"ehsan hajsafi": "Sepahan",
"shojae khalilzadeh": "Tractor",
"milad mohammadi": "Persepolis",
"saeid ezatolahi": "Shabab Al Ahli",
"alireza jahanbakhsh": "Dender",
"mohammad mohebi": "Rostov",
"mehdi taremi": "Olympiacos",
"mehdi ghayedi": "Al Nasr",
"ali alipour": "Persepolis",
"payam niazmand": "Persepolis",
"hossein kanaanizadegan": "Persepolis",
"saman ghoddos": "Kalba",
"rouzbeh cheshmi": "Esteghlal",
"mehdi torabi": "Tractor",
"aria yousefi": "Sepahan",
"amirhossein hosseinzadeh": "Tractor",
"ali nemati": "Foolad",
"shahriyar moghanlou": "Kalba",
"mohammad ghorbani": "Al Wahda",
"hossein hosseini": "Sepahan",
"ramin rezaeian": "Foolad",
"dennis eckert": "Standard Liège",
"danial eiri": "Malavan",
"amirmohammad razzaghinia": "Esteghlal",
"max crocombe": "Millwall",
"tim payne": "Wellington Phoenix",
"francis de vries": "Auckland FC",
"tyler bindon": "Sheffield United",
"michael boxall": "Minnesota United FC",
"joe bell": "Viking",
"matthew garbett": "Peterborough United",
"marko stamenic": "Swansea City",
"chris wood": "Nottingham Forest",
"sarpreet singh": "Wellington Phoenix",
"elijah just": "Motherwell",
"alex paulsen": "Lechia Gdańsk",
"liberato cacace": "Wrexham",
"alex rufer": "Wellington Phoenix",
"nando pijnaker": "Auckland FC",
"finn surman": "Portland Timbers",
"kosta barbarouses": "Western Sydney Wanderers",
"ben waine": "Port Vale",
"ben old": "Saint-Étienne",
"callum mccowatt": "Silkeborg",
"jesse randall": "Auckland FC",
"michael woud": "Auckland FC",
"ryan thomas": "PEC Zwolle",
"callan elliot": "Auckland FC",
"lachlan bayliss": "Newcastle Jets",
"tommy smith": "Braintree Town",
"vozinha": "Chaves",
"stopira": "Torreense",
"diney": "Al Bataeh",
"roberto lopes": "Shamrock Rovers",
"logan costa": "Villarreal",
"kevin pina": "Krasnodar",
"jovane cabral": "Estrela Amadora",
"joao paulo": "FCSB",
"gilson benchimol": "Akron Tolyatti",
"jamiro monteiro": "PEC Zwolle",
"garry rodrigues": "Apollon Limassol",
"marcio rosa": "Montana",
"sidny lopes cabral": "Benfica",
"deroy duarte": "Ludogorets Razgrad",
"laros duarte": "Puskás Akadémia",
"yannick semedo": "Farense",
"willy semedo": "Omonia",
"telmo arcanjo": "Vitória de Guimarães",
"dailon livramento": "Casa Pia",
"ryan mendes": "Iğdır",
"nuno da costa": "İstanbul Başakşehir",
"steven moreira": "Columbus Crew",
"cj dos santos": "San Diego FC",
"wagner pina": "Trabzonspor",
"kelvin pires": "SJK",
"helio varela": "Maccabi Tel Aviv",
"nawaf alaqidi": "Al-Nassr",
"ali majrashi": "Al-Ahli",
"ali lajami": "Al-Hilal",
"abdulelah alamri": "Al-Nassr",
"hassan altambakti": "Al-Hilal",
"nasser aldawsari": "Al-Hilal",
"musab aljuwayr": "Al-Qadsiah",
"ayman yahya": "Al-Nassr",
"firas alburaikan": "Al-Ahli",
"salem aldawsari": "Al-Hilal",
"saleh alshehri": "Al-Ittihad",
"saud abdulhamid": "Lens",
"nawaf boushal": "Al-Nassr",
"hassan kadesh": "Al-Ittihad",
"abdullah alkhaibari": "Al-Nassr",
"ziyad aljohani": "Al-Ahli",
"khalid alghannam": "Al-Ettifaq",
"alaa alhejji": "Neom",
"abdullah alhamdan": "Al-Nassr",
"sultan mandash": "Al-Hilal",
"mohammed alowais": "Al-Ula",
"ahmed alkassar": "Al-Qadsiah",
"mohamed kanno": "Al-Hilal",
"moteb alharbi": "Al-Hilal",
"jehad thakri": "Al-Qadsiah",
"mohammed abu alshamat": "Al-Qadsiah",
"david raya": "Arsenal",
"marc pubill": "Atlético Madrid",
"alex grimaldo": "Bayer Leverkusen",
"eric garcia": "Barcelona",
"marcos llorente": "Atlético Madrid",
"mikel merino": "Arsenal",
"ferran torres": "Barcelona",
"fabian ruiz": "Paris Saint-Germain",
"gavi": "Barcelona",
"dani olmo": "Barcelona",
"yeremy pino": "Crystal Palace",
"pedro porro": "Tottenham Hotspur",
"joan garcia": "Barcelona",
"aymeric laporte": "Athletic Bilbao",
"alex baena": "Atlético Madrid",
"rodri": "Manchester City",
"nico williams": "Athletic Bilbao",
"martin zubimendi": "Arsenal",
"lamine yamal": "Barcelona",
"pedri": "Barcelona",
"mikel oyarzabal": "Real Sociedad",
"pau cubarsi": "Barcelona",
"unai simon": "Athletic Bilbao",
"marc cucurella": "Chelsea",
"victor munoz": "Osasuna",
"borja iglesias": "Celta Vigo",
"sergio rochet": "Internacional",
"jose maria gimenez": "Atlético Madrid",
"sebastian caceres": "América",
"ronald araujo": "Barcelona",
"manuel ugarte": "Manchester United",
"rodrigo bentancur": "Tottenham Hotspur",
"nicolas de la cruz": "Flamengo",
"federico valverde": "Real Madrid",
"darwin nunez": "Al-Hilal",
"giorgian de arrascaeta": "Flamengo",
"facundo pellistri": "Panathinaikos",
"santiago mele": "Monterrey",
"guillermo varela": "Flamengo",
"agustin canobbio": "Fluminense",
"emiliano martinez": "Aston Villa",
"mathias olivera": "Napoli",
"matias vina": "River Plate",
"brian rodriguez": "América",
"rodrigo aguirre": "Tigres UANL",
"maximiliano araujo": "Sporting CP",
"federico vinas": "Oviedo",
"joaquin piquerez": "Palmeiras",
"fernando muslera": "Estudiantes",
"santiago bueno": "Wolverhampton Wanderers",
"juan manuel sanabria": "Real Salt Lake",
"rodrigo zalazar": "Braga",
"brice samba": "Rennes",
"malo gusto": "Chelsea",
"lucas digne": "Aston Villa",
"dayot upamecano": "Bayern Munich",
"jules kounde": "Barcelona",
"manu kone": "Roma",
"ousmane dembele": "Paris Saint-Germain",
"aurelien tchouameni": "Real Madrid",
"marcus thuram": "Inter Milan",
"kylian mbappe": "Real Madrid",
"michael olise": "Bayern Munich",
"bradley barcola": "Paris Saint-Germain",
"ngolo kante": "Fenerbahçe",
"adrien rabiot": "Milan",
"ibrahima konate": "Liverpool",
"mike maignan": "Milan",
"william saliba": "Arsenal",
"warren zaireemery": "Paris Saint-Germain",
"theo hernandez": "Al-Hilal",
"desire doue": "Paris Saint-Germain",
"lucas hernandez": "Paris Saint-Germain",
"jeanphilippe mateta": "Crystal Palace",
"robin risser": "Lens",
"rayan cherki": "Manchester City",
"maghnes akliouche": "Monaco",
"maxence lacroix": "Crystal Palace",
"fahad talib": "Al-Talaba",
"rebin sulaka": "Port",
"hussein ali": "Pogoń Szczecin",
"zaid tahseen": "Pakhtakor",
"akam hashim": "Al-Zawraa",
"manaf younis": "Al-Shorta",
"youssef amyn": "AEK Larnaca",
"ibrahim bayesh": "Al Dhafra",
"ali alhamadi": "Luton Town",
"mohanad ali": "Dibba",
"ahmed qasem": "Nashville SC",
"jalal hassan": "Al-Zawraa",
"ali yousif": "Al-Talaba",
"zidane iqbal": "Utrecht",
"ahmed maknzi": "Al-Karma",
"amir alammari": "Cracovia",
"ali jasim": "Al-Najma",
"aymen hussein": "Al-Karma",
"kevin yakob": "AGF",
"aimar sher": "Sarpsborg 08",
"marko farji": "Venezia",
"ahmed basil": "Al-Shorta",
"merchas doski": "Viktoria Plzeň",
"zaid ismail": "Al-Talaba",
"mustafa saadoon": "Al-Shorta",
"frans putros": "Persib",
"rjan nyland": "Sevilla",
"morten thorsby": "Cremonese",
"kristoffer ajer": "Brentford",
"leo stigard": "Genoa",
"david mller wolfe": "Wolverhampton Wanderers",
"patrick berg": "Bodø/Glimt",
"alexander srloth": "Atlético Madrid",
"sander berge": "Fulham",
"erling haaland": "Manchester City",
"martin degaard": "Arsenal",
"jrgen strand larsen": "Crystal Palace",
"sander tangvik": "Hamburger SV",
"egil selvik": "Watford",
"fredrik aursnes": "Benfica",
"fredrik andre bjrkan": "Bodø/Glimt",
"marcus holmgren pedersen": "Torino",
"torbjrn heggem": "Bologna",
"kristian thorstvedt": "Sassuolo",
"thelo aasgaard": "Rangers",
"antonio nusa": "RB Leipzig",
"andreas schjelderup": "Benfica",
"oscar bobb": "Fulham",
"jens petter hauge": "Bodø/Glimt",
"sondre langas": "Derby County",
"henrik falchener": "Viking",
"julian ryerson": "Borussia Dortmund",
"yehvann diouf": "Nice",
"mamadou sarr": "Chelsea",
"kalidou koulibaly": "Al-Hilal",
"abdoulaye seck": "Maccabi Haifa",
"idrissa gueye": "Everton",
"pathe ciss": "Rayo Vallecano",
"assane diao": "Como",
"lamine camara": "Monaco",
"bamba dieng": "Lorient",
"sadio mane": "Al-Nassr",
"nicolas jackson": "Bayern Munich",
"cherif ndiaye": "Samsunspor",
"iliman ndiaye": "Everton",
"ismail jakobs": "Galatasaray",
"krepin diatta": "Monaco",
"edouard mendy": "Al-Ahli",
"pape matar sarr": "Tottenham Hotspur",
"ismaila sarr": "Crystal Palace",
"moussa niakhate": "Lyon",
"ibrahim mbaye": "Paris Saint-Germain",
"habib diarra": "Sunderland",
"bara sapoko ndiaye": "Bayern Munich",
"mory diaw": "Le Havre",
"antoine mendy": "Nice",
"el hadji malick diouf": "West Ham United",
"pape gueye": "Villarreal",
"melvin mastil": "Stade Nyonnais",
"aissa mandi": "Lille",
"achref abada": "USM Alger",
"mohamed amine tougai": "Espérance de Tunis",
"zineddine belaid": "JS Kabylie",
"ramiz zerrouki": "Twente",
"riyad mahrez": "Al-Ahli",
"houssem aouar": "Al-Ittihad",
"amine gouiri": "Marseille",
"fares chaibi": "Eintracht Frankfurt",
"anis hadj moussa": "Feyenoord",
"nadhir benbouali": "Győri ETO",
"jaouen hadjam": "Young Boys",
"hicham boudaoui": "Nice",
"rayan aitnouri": "Manchester City",
"oussama benbot": "USM Alger",
"rafik belghali": "Hellas Verona",
"mohamed amoura": "VfL Wolfsburg",
"nabil bentaleb": "Lille",
"adil boulbina": "Al-Duhail",
"ramy bensebaini": "Borussia Dortmund",
"ibrahim maza": "Bayer Leverkusen",
"luca zidane": "Granada",
"yacine titraoui": "Charleroi",
"fares ghedjemis": "Frosinone",
"samir chergui": "Paris FC",
"juan musso": "Atlético Madrid",
"marcos senesi": "Bournemouth",
"nicolas tagliafico": "Lyon",
"gonzalo montiel": "River Plate",
"leandro paredes": "Boca Juniors",
"lisandro martinez": "Manchester United",
"rodrigo de paul": "Inter Miami CF",
"valentin barco": "Strasbourg",
"julian alvarez": "Atlético Madrid",
"lionel messi": "Inter Miami CF",
"giovani lo celso": "Real Betis",
"geronimo rulli": "Marseille",
"cristian romero": "Tottenham Hotspur",
"exequiel palacios": "Bayer Leverkusen",
"nicolas gonzalez": "Atlético Madrid",
"thiago almada": "Atlético Madrid",
"giuliano simeone": "Atlético Madrid",
"nico paz": "Como",
"nicolas otamendi": "Benfica",
"alexis mac allister": "Liverpool",
"jose manuel lopez": "Palmeiras",
"lautaro martinez": "Inter Milan",
"enzo fernandez": "Chelsea",
"facundo medina": "Marseille",
"nahuel molina": "Atlético Madrid",
"alexander schlager": "Red Bull Salzburg",
"david affengruber": "Elche",
"kevin danso": "Tottenham Hotspur",
"xaver schlager": "RB Leipzig",
"stefan posch": "Mainz 05",
"nicolas seiwald": "RB Leipzig",
"marko arnautovic": "Red Star Belgrade",
"david alaba": "Real Madrid",
"marcel sabitzer": "Borussia Dortmund",
"florian grillitsch": "Braga",
"michael gregoritsch": "FC Augsburg",
"florian wiegele": "Viktoria Plzeň",
"patrick pentz": "Brøndby",
"sasa kalajdzic": "LASK",
"philipp lienhart": "SC Freiburg",
"phillipp mwene": "Mainz 05",
"carney chukwuemeka": "Borussia Dortmund",
"romano schmid": "Werder Bremen",
"dejan ljubicic": "Schalke 04",
"konrad laimer": "Bayern Munich",
"patrick wimmer": "VfL Wolfsburg",
"alexander prass": "TSG Hoffenheim",
"marco friedl": "Werder Bremen",
"paul wanner": "PSV Eindhoven",
"michael svoboda": "Venezia",
"alessandro schopf": "Wolfsberger AC",
"yazeed abulaila": "Al-Hussein",
"mohammad abu hashish": "Al-Karma",
"abdallah nasib": "Al-Zawraa",
"husam abu dahab": "Al-Faisaly",
"yazan alarab": "FC Seoul",
"amer jamous": "Al-Zawraa",
"mohammad abu zrayq": "Raja Casablanca",
"noor alrawabdeh": "Selangor",
"ali olwan": "Al-Sailiya",
"musa altaamari": "Rennes",
"odeh alfakhouri": "Pyramids",
"nour bani attiah": "Al-Faisaly",
"mahmoud almardi": "Al-Hussein",
"rajaei ayed": "Al-Hussein",
"ibrahim sadeh": "Al-Karma",
"mo abualnadi": "Selangor",
"salim obaid": "Al-Hussein",
"mohammad taha": "Al-Hussein",
"saed alrosan": "Al-Hussein",
"mohannad abu taha": "Al-Quwa Al-Jawiya",
"nizar alrashdan": "Qatar SC",
"abdallah alfakhouri": "Al-Wehdat",
"ihsan haddad": "Al-Hussein",
"ali azaizeh": "Al-Shabab",
"mohammad aldawoud": "Al-Wehdat",
"anas badawi": "Al-Faisaly",
"david ospina": "Atlético Nacional",
"daniel munoz": "Crystal Palace",
"jhon lucumi": "Bologna",
"santiago arias": "Independiente",
"kevin castano": "River Plate",
"richard rios": "Benfica",
"luis diaz": "Bayern Munich",
"jorge carrascal": "Flamengo",
"jhon cordoba": "Krasnodar",
"james rodriguez": "Minnesota United FC",
"jhon arias": "Palmeiras",
"camilo vargas": "Atlas",
"yerry mina": "Cagliari",
"gustavo puerta": "Racing Santander",
"juan portilla": "Athletico Paranaense",
"jefferson lerma": "Crystal Palace",
"johan mojica": "Mallorca",
"willer ditta": "Cruz Azul",
"cucho hernandez": "Real Betis",
"juan fernando quintero": "River Plate",
"jaminton campaz": "Rosario Central",
"deiver machado": "Nantes",
"davinson sanchez": "Galatasaray",
"alvaro montero": "Vélez Sarsfield",
"luis suarez": "Sporting CP",
"andres gomez": "Vasco da Gama",
"lionel mpasi": "Le Havre",
"aaron wanbissaka": "West Ham United",
"steve kapuadi": "Widzew Łódź",
"axel tuanzebe": "Burnley",
"dylan batubinsika": "AEL",
"ngalayel mukau": "Lille",
"nathanael mbuku": "Montpellier",
"samuel moutoussamy": "Atromitos",
"brian cipenga": "Castellón",
"theo bongonda": "Spartak Moscow",
"gael kakuta": "AEL",
"joris kayembe": "Genk",
"meschak elia": "Alanyaspor",
"noah sadiki": "Sunderland",
"aaron tshibola": "Kilmarnock",
"timothy fayulu": "Noah",
"cedric bakambu": "Real Betis",
"charles pickel": "Espanyol",
"fiston mayele": "Pyramids",
"yoane wissa": "Newcastle United",
"matthieu epolo": "Standard Liège",
"chancel mbemba": "Lille",
"simon banza": "Al Jazira",
"gedeon kalulu": "Aris Limassol",
"edo kayembe": "Watford",
"arthur masuaku": "Lens",
"diogo costa": "Porto",
"nelson semedo": "Fenerbahçe",
"ruben dias": "Manchester City",
"tomas araujo": "Benfica",
"diogo dalot": "Manchester United",
"matheus nunes": "Manchester City",
"cristiano ronaldo": "Al-Nassr",
"bruno fernandes": "Manchester United",
"goncalo ramos": "Paris Saint-Germain",
"bernardo silva": "Manchester City",
"joao felix": "Al-Nassr",
"jose sa": "Wolverhampton Wanderers",
"renato veiga": "Villarreal",
"goncalo inacio": "Sporting CP",
"joao neves": "Paris Saint-Germain",
"francisco trincao": "Sporting CP",
"rafael leao": "Milan",
"pedro neto": "Chelsea",
"goncalo guedes": "Real Sociedad",
"joao cancelo": "Barcelona",
"ruben neves": "Al-Hilal",
"rui silva": "Sporting CP",
"vitinha": "Paris Saint-Germain",
"samu costa": "Mallorca",
"nuno mendes": "Paris Saint-Germain",
"francisco conceicao": "Juventus",
"utkir yusupov": "Navbahor Namangan",
"abdukodir khusanov": "Manchester City",
"khojiakbar alijonov": "Pakhtakor",
"farrukh sayfiev": "Neftchi Fergana",
"rustam ashurmatov": "Esteghlal",
"akmal mozgovoy": "Pakhtakor",
"otabek shukurov": "Baniyas",
"jamshid iskanderov": "Neftchi Fergana",
"odiljon hamrobekov": "Tractor",
"jaloliddin masharipov": "Esteghlal",
"oston urunov": "Persepolis",
"abduvohid nematov": "Nasaf",
"sherzod nasrullaev": "Nasaf",
"eldor shomurodov": "İstanbul Başakşehir",
"umar eshmurodov": "Nasaf",
"botirali ergashev": "Neftchi Fergana",
"dostonbek khamdamov": "Pakhtakor",
"abdulla abdullaev": "Dibba",
"azizjon ganiev": "Al Bataeh",
"azizbek amonov": "Dinamo Samarqand",
"igor sergeev": "Persepolis",
"abbosbek fayzullaev": "İstanbul Başakşehir",
"sherzod esanov": "Bukhara",
"bekhruz karimov": "Surkhon Termiz",
"avazbek ulmasaliev": "AGMK",
"jakhongir urozov": "Dinamo Samarqand",
"dominik livakovic": "Dinamo Zagreb",
"josip stanisic": "Bayern Munich",
"marin pongracic": "Fiorentina",
"josko gvardiol": "Manchester City",
"duje caletacar": "Real Sociedad",
"josip sutalo": "Ajax",
"nikola moro": "Bologna",
"mateo kovacic": "Manchester City",
"andrej kramaric": "TSG Hoffenheim",
"luka modric": "Milan",
"ante budimir": "Osasuna",
"ivor pandur": "Hull City",
"nikola vlasic": "Torino",
"ivan perisic": "PSV Eindhoven",
"mario pasalic": "Atalanta",
"martin baturina": "Como",
"petar sucic": "Inter Milan",
"kristijan jakic": "FC Augsburg",
"toni fruk": "Rijeka",
"igor matanovic": "SC Freiburg",
"luka sucic": "Real Sociedad",
"luka vuskovic": "Hamburger SV",
"dominik kotarski": "Copenhagen",
"marco pasalic": "Orlando City SC",
"martin erlic": "Midtjylland",
"petar musa": "FC Dallas",
"jordan pickford": "Everton",
"ezri konsa": "Aston Villa",
"nico oreilly": "Manchester City",
"declan rice": "Arsenal",
"john stones": "Manchester City",
"marc guehi": "Manchester City",
"bukayo saka": "Arsenal",
"elliot anderson": "Nottingham Forest",
"harry kane": "Bayern Munich",
"jude bellingham": "Real Madrid",
"marcus rashford": "Barcelona",
"tino livramento": "Newcastle United",
"dean henderson": "Crystal Palace",
"jordan henderson": "Brentford",
"dan burn": "Newcastle United",
"kobbie mainoo": "Manchester United",
"morgan rogers": "Aston Villa",
"anthony gordon": "Newcastle United",
"ollie watkins": "Aston Villa",
"noni madueke": "Arsenal",
"eberechi eze": "Arsenal",
"ivan toney": "Al-Ahli",
"james trafford": "Manchester City",
"reece james": "Chelsea",
"djed spence": "Tottenham Hotspur",
"jarell quansah": "Bayer Leverkusen",
"lawrence atizigi": "St. Gallen",
"alidu seidu": "Rennes",
"caleb yirenkyi": "Nordsjælland",
"jonas adjetey": "VfL Wolfsburg",
"thomas partey": "Villarreal",
"abdul mumin": "Rayo Vallecano",
"abdul fatawu": "Leicester City",
"kwasi sibo": "Oviedo",
"jordan ayew": "Leicester City",
"brandon thomasasante": "Coventry City",
"antoine semenyo": "Manchester City",
"joseph anang": "St Patrick's Athletic",
"christopher bonsu baah": "Al-Qadsiah",
"gideon mensah": "Auxerre",
"elisha owusu": "Auxerre",
"benjamin asare": "Hearts of Oak",
"abdul rahman baba": "PAOK",
"jerome opoku": "İstanbul Başakşehir",
"inaki williams": "Athletic Bilbao",
"augustine boakye": "Saint-Étienne",
"kojo peprah oppong": "Nice",
"kamaldeen sulemana": "Atalanta",
"derrick luckassen": "Pafos",
"ernest nuamah": "Lyon",
"prince kwabena adu": "Viktoria Plzeň",
"marvin senaya": "Auxerre",
"luis mejia": "Nacional",
"cesar blackman": "Slovan Bratislava",
"jose cordoba": "Norwich City",
"fidel escobar": "Saprissa",
"edgardo farina": "Pari Nizhny Novgorod",
"cristian martinez": "Ironi Kiryat Shmona",
"jose luis rodriguez": "Juárez",
"adalberto carrasquilla": "Pumas UNAM",
"tomas rodriguez": "Saprissa",
"ismael diaz": "León",
"yoel barcenas": "Mazatlán",
"cesar samudio": "Marathón",
"jiovany ramos": "Puerto Cabello",
"carlos harvey": "Minnesota United FC",
"eric davis": "Plaza Amador",
"andres andrade": "LASK",
"jose fajardo": "Universidad Católica",
"cecilio waterman": "Universidad de Concepción",
"alberto quintero": "Plaza Amador",
"anibal godoy": "San Diego FC",
"cesar yanis": "Cobresal",
"orlando mosquera": "Al-Fayha",
"michael amir murillo": "Beşiktaş",
"azarias londono": "Universidad Católica",
"roderick miller": "Turan Tovuz",
"jorge gutierrez": "Deportivo La Guaira"
};
